name: songs-recommender-system-env

dependencies:
	- python=3.10
    - ipykernel=6.23.1 
  	- beautifulsoup4=4.12.0
    - matplotlib=3.7.1
    - mplsoccer=1.1.12
    - numpy=1.24.3
    - pandas=2.0.1
    - Requests=2.31.0
    - scikit_learn=1.2.2
    - scipy=1.10.1
    - setuptools=67.6.1
    - spotipy=2.23.0
    - streamlit=1.22.0
    - textblob=0.17.1